formats:
  - md
  - adoc
  - rst

commands:
  build: 'cd {dir} && hugo && cd ..'
  version: hugo version

layout: |
  ---
  title: Benchmark
  date: 2019-12-29T18:09:15-08:00
  draft: false
  ---

  {content}

filename: test{0}

content: content/post
