formats:
  - md
  - adoc

commands:
  build: 'cd {dir} && bundle exec jekyll build && cd ..'

layout: |
  ---
  layout: post
  title:  "Bench"
  date:   2019-12-31 10:33:02 -0800
  categories: benchmarking
  ---

  {content}

filename: 2012-09-12-test{0}

content: _posts
