name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Vale
      uses: errata-ai/vale-action@master
      with:
        files: docs
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
